- name: Vars Demo
  hosts: all
  vars:
    URL: global.variable.com
  tasks:
    - name: Printing Variable name1
      ansible.builtin.debug:
        msg: printing global variable {{URL}}

    - name: Printing Local Variable
      ansible.builtin.debug:
        msg: printing local variable {{URL}}
      vars:
        URL: local.variable.com