- name: Var From File
  hosts: all
  vars_files:
   - 00-samplevar.yml
  tasks:
    - name: Printing Var form a different file
      ansible.builtin.debug:
        msg: Priint Variable vaule {{URL}} from a different file
